### ISSUE TITLE
Enable Travis build?

### ISSUE THREAD

**Issue by adjohnson916** [jonschlinkert/sync-pkg#16]
For some reason, the Travis build isn't running. Any ideas @jonschlinkert?

https://travis-ci.org/jonschlinkert/sync-pkg

**Comment by jonschlinkert** [comment]
sorry I never saw this issue. I'm checking now

**Comment by adjohnson916** [comment]
@jonschlinkert Looks like it's running now. Thanks!

**Comment by jonschlinkert** [comment]
thanks for checking into it. A couple of days ago, the last I saw was that travis was still failing for some reason. looks like it worked itself out!
