### ISSUE TITLE
replace filter-object with object.omit

### ISSUE THREAD

**Issue by jonschlinkert** [jonschlinkert/sync-pkg#19]
this was a nice idea, but it seems like glob filtering is probably unnecessary. @adjohnson916  in the next major bump how about if we just do a simple omit? this still allows the user to pass an array of keys to omit, but it would be less likely to yield unexpected results.

**Comment by adjohnson916** [comment]
@jonschlinkert But I like the extra power of filter-object! Downsides are what - having to escape special characters? AFAIK, most of those don't tend to appear as JSON keys in package.json or bower.json.
If we do, we could leave support for both by simply using a new option for object.omit, e.g. `-o`.

**Comment by jonschlinkert** [comment]
no reason to remove it if it's getting used! I guess I should have asked "is anyone using this feature?" lol. I need to remember it's there more often. Let's just keep it. thx for the feedback
