### ISSUE TITLE
Run in CLI

### ISSUE THREAD

**Issue by luiscruz** [jonschlinkert/sync-pkg#2]
Hi,

Thank you for this very useful tool.

How exactly am I supposed to run in CLI?
I cannot find any CLI executable in the package..

Thanks,
Luis Cruz

**Comment by adjohnson916** [comment]
@luiscruz After global npm install, per the readme, you can run `sync-pkg` from the command line. Prior to my fix today, the readme incorrectly instructed to run `sync`, but it is now corrected on the `master` branch. Thanks.
